name: Deploy Sphinx documentation to Pages

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'docs/**/*'
  push:
    branches:
      - main

jobs:
  pages:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install sphinx
        pip install sphinx-autobuild
        pip install myst-parser
        pip install sphinx_rtd_theme
        pip install sphinxcontrib.mermaid

    - id: build
      name: Build Documentation
      run: |
        cd docs/sphinx_doc
        ./build_sphinx_doc.sh
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: SphinxDoc
        path: 'docs/sphinx_doc/build'
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: 'docs/sphinx_doc/build/html'